// Shared partner companies data across the application
export const partnerCompanies = [
  { name: 'Google', domain: 'google.com', category: 'Tech' },
  { name: 'Microsoft', domain: 'microsoft.com', category: 'Tech' },
  { name: 'Amazon', domain: 'amazon.com', category: 'Tech' },
  { name: 'TCS', domain: 'tcs.com', category: 'IT Services' },
  { name: 'Infosys', domain: 'infosys.com', category: 'IT Services' },
  { name: 'Wipro', domain: 'wipro.com', category: 'IT Services' },
  { name: 'Accenture', domain: 'accenture.com', category: 'Consulting' },
  { name: 'IBM', domain: 'ibm.com', category: 'Tech' },
  { name: 'Cognizant', domain: 'cognizant.com', category: 'IT Services' },
  { name: 'HCL', domain: 'hcltech.com', category: 'IT Services' },
  { name: 'Dell', domain: 'dell.com', category: 'Tech' },
  { name: 'Oracle', domain: 'oracle.com', category: 'Tech' },
  { name: 'Capgemini', domain: 'capgemini.com', category: 'Consulting' },
  { name: 'Tech Mahindra', domain: 'techmahindra.com', category: 'IT Services' },
  { name: 'Intel', domain: 'intel.com', category: 'Tech' },
  { name: 'Apple', domain: 'apple.com', category: 'Tech' },
  { name: 'Meta', domain: 'meta.com', category: 'Tech' },
  { name: 'Netflix', domain: 'netflix.com', category: 'Tech' },
  { name: 'Adobe', domain: 'adobe.com', category: 'Tech' },
  { name: 'Salesforce', domain: 'salesforce.com', category: 'Tech' },
  { name: 'Cisco', domain: 'cisco.com', category: 'Tech' },
  { name: 'HP', domain: 'hp.com', category: 'Tech' },
  { name: 'NVIDIA', domain: 'nvidia.com', category: 'Tech' },
  { name: 'SAP', domain: 'sap.com', category: 'Tech' },
  { name: 'Deloitte', domain: 'deloitte.com', category: 'Consulting' },
  { name: 'PwC', domain: 'pwc.com', category: 'Consulting' },
  { name: 'EY', domain: 'ey.com', category: 'Consulting' },
  { name: 'KPMG', domain: 'kpmg.com', category: 'Consulting' },
  { name: 'Goldman Sachs', domain: 'goldmansachs.com', category: 'Finance' },
  { name: 'JP Morgan', domain: 'jpmorgan.com', category: 'Finance' },
  { name: 'Flipkart', domain: 'flipkart.com', category: 'E-commerce' },
  { name: 'Zomato', domain: 'zomato.com', category: 'Tech' },
  { name: 'Paytm', domain: 'paytm.com', category: 'FinTech' },
  { name: 'Zoho', domain: 'zoho.com', category: 'Tech' },
]

